### PR TITLE
Support hapi 17

### PR DESCRIPTION
**Pull request by anthony-dibenedetto-olx**
**What does this PR do?**

- Adds support for Hapi 17

Related to issue #24

### CODE REVIEW

**Comment by anthony-dibenedetto-olx** [comment]
@chapel @hueniverse 

Should I update also the `.travis.yml` file?

**Comment by hueniverse** [comment]
Yep, to match the other modules.

**Comment by anthony-dibenedetto-olx** [comment]
@hueniverse 

Updated **travis** file. Also made some refactors a fixed some tests to reach 100% coverage

**Comment by anthony-dibenedetto-olx** [comment]
@hueniverse @chapel 

Could you take a look at this PR? Thanks!

**Comment by hueniverse** [comment]
Need to find someone who uses this to review.

**Comment by jamesgibson14** [comment]
I have tested this out with my app and the caching is working, one thing I noticed though is that if the memcached server goes down after startup this.isConnected is still true so the request just gets stuck with no timeout/error

**Comment by hueniverse** [comment]
@anthony-dibenedetto-olx Can you look into this issue?

**Comment by iniva** [comment]
@hueniverse 
Yes I can take a look.

Meanwhile @jamesgibson14 if you want to help I wouldn't mind.

Eran, how do I / we proceed on this case? This PR is still unmerged and if James wanted to help he wouldn't be able to send a PR, unless it is against this branch.

Another thing I noticed is that this module doesn't have releases, unlike the other catbox-* modules. Is there a reason for that?

**Comment by hueniverse** [comment]
I was unable to get any response from @chapel who is the only one with access rights on npm. I've emailed him and waiting to hear back. You should be able to merge the code to the repo though. Let me know if you were not added (via your personal account as requested).

**Comment by iniva** [comment]
@hueniverse yes, I can merge the code. I'll do that

**Pull request merged**
